# Generated by Django 4.0.4 on 2022-04-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.CharField(max_length=4000),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
