# Generated by Django 4.0.4 on 2022-04-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('user', 'event')},
        ),
    ]
