# Generated by Django 4.0.4 on 2022-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.CharField(max_length=40000),
        ),
    ]
