# Generated by Django 4.0.4 on 2022-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='message',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
