# Generated by Django 4.0.4 on 2022-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_reaction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='availibility_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
