# Generated by Django 4.0.4 on 2022-05-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_reaction_availibility_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.CharField(max_length=4000000),
        ),
    ]
